export const ASSIGN_HEADER_TITLE = 'ASSIGN_HEADER_TITLE';

//Planter
export const ADD_PLANTER = 'ADD_PLANTER';
export const REMOVE_PLANTER = 'REMOVE_PLANTER';
export const UPDATE_PLANTER = 'UPDATE_PLANTER';

//Request Key
export const ADD_REQUEST_KEY = 'ADD_REQUEST_KEY';
export const REMOVE_REQUEST_KEY = 'REMOVE_REQUEST_KEY';
export const UPDATE_REQUEST_KEY = 'UPDATE_REQUEST_KEY';

//Block
export const ADD_BLOCK = 'ADD_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const UPDATE_BLOCK = 'UPDATE_BLOCK';

//Contract
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const REMOVE_CONTRACT = 'REMOVE_CONTRACT';
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';

//Date
export const ADD_TALLY_DATE = 'ADD_TALLY_DATE';

//Planter Relations

//Request Key Relations

//Block Relations
export const ADD_REQUEST_KEY_TO_BLOCK = 'ADD_REQUEST_KEY_TO_BLOCK';
export const REMOVE_REQUEST_KEY_FROM_BLOCK = 'REMOVE_REQUEST_KEY_FROM_BLOCK';

//Contract Relations
export const ADD_BLOCK_TO_CONTRACT = 'ADD_BLOCK_TO_CONTRACT';
export const REMOVE_BLOCK_FROM_CONTRACT = 'REMOVE_BLOCK_FROM_CONTRACT';

//Date Relations
export const ADD_PLANTER_TO_TALLY_DATE = 'ADD_PLANTER_TO_TALLY_DATE';
export const REMOVE_PLANTER_FROM_TALLY_DATE = 'REMOVE_PLANTER_FROM_TALLY_DATE';
export const ADD_REQUEST_KEY_TO_TALLY_DATE = 'ADD_REQUEST_KEY_TO_TALLY_DATE';
export const REMOVE_REQUEST_KEY_FROM_TALLY_DATE = 'REMOVE_REQUEST_KEY_FROM_TALLY_DATE';
export const ADD_BLOCK_TO_TALLY_DATE = 'ADD_BLOCK_TO_TALLY_DATE';
export const REMOVE_BLOCK_FROM_TALLY_DATE = 'REMOVE_BLOCK_FROM_TALLY_DATE';
export const ADD_CONTRACT_TO_TALLY_DATE = 'ADD_CONTRACT_TO_TALLY_DATE';
export const REMOVE_CONTRACT_FROM_TALLY_DATE = 'REMOVE_CONTRACT_FROM_TALLY_DATE';

//Setting Selected
export const SET_SELECTED_PLANTER_ID = 'SET_SELECTED_PLANTER_ID';
export const SET_SELECTED_CONTRACT_ID = 'SET_SELECTED_CONTRACT_ID';
export const SET_SELECTED_BLOCK_ID = 'SET_SELECTED_BLOCK_ID';
export const SET_SELECTED_REQUEST_KEY_ID = 'SET_SELECTED_REQUEST_KEY_ID';
export const SET_SELECTED_TALLY_DATE = 'SET_SELECTED_TALLY_DATE';
